### ISSUE TITLE
Open source code

### ISSUE THREAD

**Issue by qibin0506** [taco-group/OpenEMMA#1]
Hello, when to open source the code?

**Comment by chirayu2107** [comment]
Open source your code when it’s stable, useful, and well-documented, with a clear license and no sensitive data. Be ready to engage with the community and maintain it actively.

**Comment by vztu** [comment]
ETA is next week before Thanksgiving break! Thanks for your patience!

**Comment by vztu** [comment]
Our code has been released as of today! @qibin0506  @chirayu2107
