### ISSUE TITLE
Question Regarding the Correct Execution of the Code

### ISSUE THREAD

**Issue by zhangye0402** [taco-group/OpenEMMA#3]
Thank you for sharing this project! I have followed your instructions to run the code, but it seems that the program is not executing correctly. Could there be an issue with the code? I would greatly appreciate it if you could take a look.

Thank you for your time and assistance!

**Comment by vztu** [comment]
Can you provide the exact error you encountered?

**Comment by BigBoomDream** [comment]
> Can you provide the exact error you encountered?

Hi, I noticed there is a typo in the import statement in OpenEMMA/main.py at line 19:

from OpenEMMA.utils import EstimateCurvatureFromTrajeemmary

However, in utils.py, the actual function name is EstimateCurvatureFromTrajecotry. This discrepancy causes an ImportError when running the code. The error message is as follows:

ImportError: cannot import name 'EstimateCurvatureFromTrajeemmary' from 'OpenEMMA.utils' (/data1/wjx/OpenEMMA/utils.py)
Could you please confirm and correct this issue? Thank you for your work on this project!

**Comment by BigBoomDream** [comment]
> Can you provide the exact error you encountered?

Hi, I noticed there is a typo in the import statement in **OpenEMMA/main.py** at line 19:

from OpenEMMA.utils import EstimateCurvatureFromTrajeemmary
However, in utils.py, the actual function name is EstimateCurvatureFromTrajecotry. This discrepancy causes an ImportError when running the code. The error message is as follows:

ImportError: cannot import name 'EstimateCurvatureFromTrajeemmary' from 'OpenEMMA.utils' (/data1/wjx/OpenEMMA/utils.py)
Could you please confirm and correct this issue? Thank you for your work on this project!

**Comment by BigBoomDream** [comment]
> Can you provide the exact error you encountered?

Title: Typo in Import Statement in main.py (Line 19)

Description:

Hi, I noticed there is a typo in the import statement in **OpenEMMA/main.py** at line 19:

`from OpenEMMA.utils import EstimateCurvatureFromTrajeemmary`

However, in **utils.py**, the actual function name is **EstimateCurvatureFromTrajecotry**. This discrepancy causes an ImportError when running the code. The error message is as follows:

``` ImportError: cannot import name 'EstimateCurvatureFromTrajeemmary' from 'OpenEMMA.utils'  ```

Could you please confirm and correct this issue? Thank you for your work on this project!

**Comment by BigBoomDream** [comment]
> Can you provide the exact error you encountered?

Hi, I noticed there is a typo in the import statement in `OpenEMMA/main.py` at line 19:  

```python
from OpenEMMA.utils import EstimateCurvatureFromTrajeemmary

However, in utils.py, the actual function name is EstimateCurvatureFromTrajecotry. This discrepancy causes an ImportError when running the code. The error message is as follows:

ImportError: cannot import name 'EstimateCurvatureFromTrajeemmary' from 'OpenEMMA.utils' (/data1/wjx/OpenEMMA/utils.py)

Could you please confirm and correct this issue? Thank you for your work on this project!

**Comment by BigBoomDream** [comment]
> Can you provide the exact error you encountered?

Hi, I noticed there is a typo in the import statement in `OpenEMMA/main.py` at line 19:  

`from OpenEMMA.utils import EstimateCurvatureFromTrajeemmary`

However, in **utils.py**, the actual function name is **EstimateCurvatureFromTrajecotry**. 

This discrepancy causes an ImportError when running the code. The error message is as follows:
`ImportError: cannot import name 'EstimateCurvatureFromTrajeemmary' from 'OpenEMMA.utils' `

Could you please confirm and correct this issue? Thank you for your work on this project!

**Comment by BigBoomDream** [comment]
@vztu
 Hi, I noticed there is a typo in the import statement in OpenEMMA/main.py at line 19:

from OpenEMMA.utils import EstimateCurvatureFromTrajeemmary

However, in utils.py, the actual function name is EstimateCurvatureFromTrajecotry.

This discrepancy causes an ImportError when running the code. The error message is as follows:
ImportError: cannot import name 'EstimateCurvatureFromTrajeemmary' from 'OpenEMMA.utils' 

Could you please confirm and correct this issue? Thank you for your work on this project!

**Comment by BigBoomDream** [comment]
@vztu
Hi, I noticed there is a typo in the import statement in **OpenEMMA/main.py** at line 19:

`from OpenEMMA.utils import **EstimateCurvatureFromTrajeemmary**`

However, in **utils.py**, the actual function name is **EstimateCurvatureFromTrajecotry**.

This discrepancy causes an ImportError when running the code. The error message is as follows:
`ImportError: cannot import name 'EstimateCurvatureFromTrajeemmary' from 'OpenEMMA.utils'`

Could you please confirm and correct this issue? Thank you for your work on this project!

**Comment by zhangye0402** [comment]
> @vztu Hi, I noticed there is a typo in the import statement in **OpenEMMA/main.py** at line 19:
> 
> `from OpenEMMA.utils import **EstimateCurvatureFromTrajeemmary**`
> 
> However, in **utils.py**, the actual function name is **EstimateCurvatureFromTrajecotry**.
> 
> This discrepancy causes an ImportError when running the code. The error message is as follows: `ImportError: cannot import name 'EstimateCurvatureFromTrajeemmary' from 'OpenEMMA.utils'`
> 
> Could you please confirm and correct this issue? Thank you for your work on this project!
I encountered the same issue as mentioned above. After modifying the function name, the code still fails to execute and raises the following error:
"No module named 'qwen_vl_utils'"

**Comment by zhangye0402** [comment]
I encountered the same issue as mentioned above. After modifying the function name, the code still fails to execute and raises the following error:
"No module named 'qwen_vl_utils'"

**Comment by BigBoomDream** [comment]
> I encountered the same issue as mentioned above. After modifying the function name, the code still fails to execute and raises the following error: "No module named 'qwen_vl_utils'"

@zhangye0402 Make sure to install the required library qwen_vl_utils by running:
`pip install qwen_vl_utils`

**Comment by ShuoXing98** [comment]
> > I encountered the same issue as mentioned above. After modifying the function name, the code still fails to execute and raises the following error: "No module named 'qwen_vl_utils'"
> 
> @zhangye0402 Make sure to install the required library qwen_vl_utils by running: `pip install qwen_vl_utils`

Thank you for your prompt response. We have added `qwen_vl_utils` to the `requirements.txt` file and will update our repository shortly.

**Comment by ShuoXing98** [comment]
Fixed issues related to execution and installation in commit 6b57f8be83d203e41dfe99b5e8690dab2ed77d6a
