### ISSUE TITLE
Issue with Qwen2-VL-7B-Instruct Model - Mismatch Between Image Features and Tokens

### ISSUE THREAD

**Issue by BigBoomDream** [taco-group/OpenEMMA#4]
First, I want to express my gratitude for your excellent work on this project. I've been struggling to find other open-source code that fits my needs, and your work came at just the right time.

However, I've encountered an issue when running the **Qwen2-VL-7B-Instruct** model. I'm seeing the following error:
`ValueError: Image features and image tokens do not match: tokens: 0, features 1824`

The error occurs after the image preprocessing step. For reference, I used an image with the following details:
Image path: `/data1/vista/data/samples/CAM_FRONT/n008-2018-08-01-15-16-36-0400__CAM_FRONT__1533151608012404.jpg`
Image size:` (1600, 900)`
Processed image shape: `[(1596, 896)]`

I initially thought this might be a resolution issue, so I tried resizing the image to **(528, 223)**, but the error persists. Interestingly, the `LLaVA-1.6-Mistral-7B` model **runs successfully** in the same environment without this problem.

Could you provide any insights into what might be causing this mismatch between the image features and tokens, or any configuration details I should check to resolve it?

Thanks again for your great work!

**Comment by BigBoomDream** [comment]
I wanted to provide an update regarding the issue I previously reported. When running the **Qwen2-VL-7B-Instruct** model on the `[Qwen2-VL-7B-Instruct demo](https://huggingface.co/Qwen/Qwen2-VL-7B-Instruct)`, it works correctly and produces the expected output.

Here are the details of my environment:
```torch: 2.1.2
python: 3.8.20
transformers: 4.46.3
qwen-vl-utils: 0.0.8
modelscope: 1.21.0```

**Comment by BigBoomDream** [comment]
> First, I want to express my gratitude for your excellent work on this project. I've been struggling to find other open-source code that fits my needs, and your work came at just the right time.
> 
> However, I've encountered an issue when running the **Qwen2-VL-7B-Instruct** model. I'm seeing the following error: `ValueError: Image features and image tokens do not match: tokens: 0, features 1824`
> 
> The error occurs after the image preprocessing step. For reference, I used an image with the following details: Image path: `/data1/vista/data/samples/CAM_FRONT/n008-2018-08-01-15-16-36-0400__CAM_FRONT__1533151608012404.jpg` Image size:` (1600, 900)` Processed image shape: `[(1596, 896)]`
> 
> I initially thought this might be a resolution issue, so I tried resizing the image to **(528, 223)**, but the error persists. Interestingly, the `LLaVA-1.6-Mistral-7B` model **runs successfully** in the same environment without this problem.
> 
> Could you provide any insights into what might be causing this mismatch between the image features and tokens, or any configuration details I should check to resolve it?
> 
> Thanks again for your great work!

I wanted to provide an update regarding the issue I previously reported. When running the **Qwen2-VL-7B-Instruct** model on the `[Qwen2-VL-7B-Instruct demo](https://huggingface.co/Qwen/Qwen2-VL-7B-Instruct)`, it works correctly and produces the expected output.

Here are the details of my environment:
```
torch: 2.1.2
python: 3.8.20
transformers: 4.46.3
qwen-vl-utils: 0.0.8
modelscope: 1.21.0
```

**Comment by Waldeinc** [comment]
main.py里的vlm_inference方法里处理qwen的这部分代码，给inputs赋值的时候，传入的text变量实际上是None，对比qwen给的示例发现漏了一句代码

**Comment by BigBoomDream** [comment]
> main.py里的vlm_inference方法里处理qwen的这部分代码，给inputs赋值的时候，传入的text变量实际上是None，对比qwen给的示例发现漏了一句代码

@Waldeinc 这是代码的输出，“Debug - message content: [{'type': 'image', 'image': '/data1/vista/data/samples/CAM_FRONT/n008-2018-08-01-15-16-36-0400__CAM_FRONT__1533151609012404.jpg'}, {'type': 'text', 'text': 'You are a autonomous driving labeller. You have access to a front-view camera images of a vehicle taken at a 0.5 second interval over the past 5 seconds. Imagine you are driving the car. What other road users should you pay attention to in the driving scene? List two or three of them, specifying its location within the image of the driving scene and provide a short description of the that road user on what it is doing, and why it is important to you.'}]”；

**Comment by Waldeinc** [comment]
> > main.py里的vlm_inference方法里处理qwen的这部分代码，给inputs赋值的时候，传入的text变量实际上是None，对比qwen给的示例发现漏了一句代码
> 
> @Waldeinc 这是代码的输出，“Debug - message content: [{'type': 'image', 'image': '/data1/vista/data/samples/CAM_FRONT/n008-2018-08-01-15-16-36-0400__CAM_FRONT__1533151609012404.jpg'}, {'type': 'text', 'text': 'You are a autonomous driving labeller. You have access to a front-view camera images of a vehicle taken at a 0.5 second interval over the past 5 seconds. Imagine you are driving the car. What other road users should you pay attention to in the driving scene? List two or three of them, specifying its location within the image of the driving scene and provide a short description of the that road user on what it is doing, and why it is important to you.'}]”；

message = 和inputs = 中间漏了这句
text = processor.apply_chat_template(message, tokenize=False, add_generation_prompt=True)

**Comment by BigBoomDream** [comment]
问题已找到！原因是** Qwen 模型直接使用了原始文本，没有经过处理**。解决方法是先**使用模板处理文本**，例如：
```
chat_text = processor.apply_chat_template(  # 处理文本，添加必要的标记
    message, 
    tokenize=False, 
    add_generation_prompt=True
)
```

**Comment by BigBoomDream** [comment]
问题已找到！原因是** Qwen 模型直接使用了原始文本**，没有经过处理。解决方法是先使用模板处理文本，例如：
```
chat_text = processor.apply_chat_template(  # 处理文本，添加必要的标记
    message, 
    tokenize=False, 
    add_generation_prompt=True
)
```

**Comment by BigBoomDream** [comment]
问题已找到！原因是**Qwen 模型直接使用了原始文本，没有经过处理**。解决方法是先使用模板处理文本，例如：
```
chat_text = processor.apply_chat_template(  # 处理文本，添加必要的标记
    message, 
    tokenize=False, 
    add_generation_prompt=True
)
```

**Comment by ShuoXing98** [comment]
Fixed issues related to execution and installation in commit 6b57f8be83d203e41dfe99b5e8690dab2ed77d6a
